"use strict";
let utils=require('../../utils')
let AccountBalanceSchema=exports.AccountBalanceSchema={
       CommandID:{
        type:'string',
        constant:'TransactionStatusQuery'
    },
    PartyA:{
        type:'number',
        required:true,
        custom:[utils.isPhoneNumberOrBusinessShortCode]
    },
    IdentifierType:{
        type:'number',
        required:true,
        allowed:[2,4]
    },
    Remarks:{
        type:'string',
        required:true,
        maxLength:100
    },
    Initiator:{
        type:'string',
        required:true
    },
    SecurityCredential:{
        type:'string',
        required:true
    },
    QueueTimeOutURL:{
        type:'url',
        required:true
    },
    ResultURL:{
        type:'url',
        required:true
    },
}