"use strict";
let utils=require('../../utils')
let B2CAccountTopUpSchema=exports.B2CAccountTopUpSchema={
    CommandID:{
        type:'string',
        constant:'BusinessPayToBulk'
    },
    Initiator:{
        type:'string',
        required:true
    },
    SecurityCredential:{
        type:'string',
        required:true
    },
    PartyA:{
        type:'number',
        required:true,
        custom:[utils.isBusinessShortCode]
    },
    SenderIdentifierType:{
        type:'number',
        constant:4
    },
    PartyB:{
        type:'number',
        required:true,
        custom:[utils.isBusinessShortCode]
    },
    RecieverIdentifierType:{
        type:'number',
        constant:4
    },
    Requester:{
        type:'number',
        custom:[utils.isISSDN]
    },
    Amount:{
        type:'number',
        required:true,
        custom:[utils.isNonNegativeOrZero]
    },
    Remarks:{
        type:'string',
        required:true,
        maxLength:100
    },
    QueueTimeOutURL:{
        type:'url',
        required:true,
    },
    ResultURL:{
        type:'url',
        required:true
    },
    AccountReference:{
        type:'number',
        required:true
    }
}
