"use strict";
let utils=require('../../utils');
let MPesaRatibaSchema=exports.MPesaRatibaSchema={
    StandingOrderName:{
        type:'string',
        required:true
    },
    StartDate:{
        type:'string',
        required:true,
        custom:[utils.isYearMonthDate]
    },
    EndDate:{
        type:'string',
        required:true,
        custom:[utils.isYearMonthDate]
    },
    BusinessShortCode:{
        type:'string',
        required:true,
        custom:[utils.isBusinessShortCode]
    },
    TransactionType:{
        type:'string',
        required:true,
        allowed:['Standing Order Customer Pay Bill','Standing Order Customer Buy Goods']
    },
    Amount:{
        type:'string',
        required:true,
        custom:[utils.isNonNegativeOrZero]
    },
    PartyA:{
        type:'string',
        required:true,
        custom:[utils.isMobileNumber]
    },
    CallBackURL:{
        type:'url',
        required:true,
    },
    AccountReference:{
        type:'string',
        required:true,
        maxLength:12
    },
    TransactionDesc:{
        type:'string',
        required:true,
        maxLength:13
    },
    Frequency:{
        type:'string',
        required:true,
        allowed:['1','2','3','4','5','6','7','8']
    },
    ReceiverPartyIdentifierType:{
        type:'string',
        required:true,
        allowed:['2','4']
    }
}