"use strict";
let utils=require('../../utils')
let ReversalsSchema=exports.ReversalsSchema={
    CommandID:{
        type:'string',
        constant:'TransactionReversal'
    },
    ReceiverParty:{
        type:'number',
        required:true,
        custom:[utils.isBusinessShortCode]
    },
    ReceiverIdentifierType:{
        type:'string',
        required:true,
    },
    Remarks:{
        type:'string',
        required:true,
    },
    Initiator:{
        type:'string',
        required:true
    },
    SecurityCredential:{
        type:'string',
        required:true
    },
    QueueTimeOutURL:{
        type:'url',
        required:true
    },
    ResultURL:{
        type:'url',
        required:true
    },
    TransactionID:{
        type:'array',
        required:true,
        custom:[utils.isStringArray]
    },
    Amount:{
        type:'array',
        required:true,
        custom:[utils.isNumberArray]
    },
    Occassion:{
        type:'string',
        required:true,
        maxLength:100
    }
}