"use strict";
let utils=require('../../utils')
let StkPushSchema=exports.StkPushSchema={
    BusinessShortCode:{
       required:true,
       type:'number',
       custom:[utils.isBusinessShortCode]
    },
    Password:{
        type:'string',
    },
    Timestamp:{
        type:'timestamp',
    },
    TransactionType:{
        required:true,
        type:'string',
        allowed:['CustomerPayBillOnline','CustomerBuyGoodsOnline']
    },
    Amount:{
        type:'number',
        required:true,
        custom:[utils.isInteger,utils.isNonNegativeOrZero]     
    },
    PartyA:{
        type:'number',
        required:true,
        custom:[utils.isMobileNumber]
    },
    PartyB:{
        type:'number',
        required:true,
        custom:[utils.isBusinessShortCode]
    },
    PhoneNumber:{
        type:'number',
        required:true,
        custom:[utils.isMobileNumber]
    },
    CallBackURL:{
        type:'url',
        required:true,
    },
    AccountReference:{
        type:'string',
        required:true,
        maxLength:12

    },
    TransactionDesc:{
        type:'string',
        required:true,
        maxLength:13
    }
}