"use strict";
let utils=require('../../utils')
let TaxRemittanceSchema=exports.TaxRemittanceSchema={
    CommandID:{
        type:'string',
        constant:'PayTaxToKRA',
    },
    Initiator:{
        type:'string',
        required:true,
    },
    SecurityCredential:{
        type:'string',
        required:true
    },
    PartyA:{
        type:'number',
        required:true,
        custom:[utils.isBusinessShortCode]
    },
    SenderIdentifierType:{
        type:'string',
        constant:'4'
    },
    PartyB:{
        type:'number',
        constant:572572
    },
    RecieverIdentifierType:{
        type:'string',
        constant:'4'
    },
    Amount:{
        type:'number',
        required:true,
        custom:[utils.isNonNegativeOrZero]
    },
    AccountReference:{
        type:'number',
        required:true,
    },
    Remarks:{
        type:'string',
        required:true,
        maxLength:100
    },
    QueueTimeOutURL:{
        type:'url',
        required:true
    },
    ResultURL:{
        type:'url',
        required:true
    }
}