"use strict";
let utils=require('../../utils')
let TransactionStatusSchema=exports.TransactionStatusSchema={
    CommandID:{
        type:'string',
        required:true,
        constant:'TransactionStatusQuery'
    },
    PartyA:{
        type:'number',
        required:true,
        custom:[utils.isPhoneNumberOrBusinessShortCode]
    },
    IdentifierType:{
        type:'number',
        required:true,
        allowed:[1,2,4]
    },
    Remarks:{
        type:'string',
        required:true,
        maxLength:100
    },
    Initiator:{
        type:'string',
        required:true
    },
    SecurityCredential:{
        type:'string',
        required:true
    },
    QueueTimeOutURL:{
        type:'url',
        required:true
    },
    TransactionID:{
        type:'string',
        required:true
    },
    ResultURL:{
        type:'url',
        required:true
    },
    Occassion:{
        type:'string',
        required:true,
        maxLength:100
    },
    OriginatorConversationID:{
        type:'string',
        required:true
    }
}